### ISSUE TITLE
Missing trading functions

### ISSUE THREAD

**Issue by daniel-brenot** [tgardiner/questrade_api#10]
Questrade has functionality for placing buy and sell orders, however this library does not have them. I may make a PR to add them, but i am curious why they were not added:

https://www.questrade.com/api/documentation/rest-operations/order-calls/accounts-id-orders

**Comment by tgardiner** [comment]
The `orders` endpoint was removed from the Questrade API a couple of years ago unfortunately.  The API currently has no functionality to place/update/cancel orders.  Looks like that might be an old link that hasn't been removed.

**Comment by saskatchewancatch** [comment]
This is a little off topic, but does anyone know if their C++ SDK is out of date? They still make it available on their API site, but executing the sample app results in it not being able to open a session. That SDK has a header that allows orders to be placed oddly.

The reason I ask here is because no one at the Questrade API support line answers my questions.

**Comment by daniel-brenot** [comment]
I don't know about the questrade api, but i am now looking into the interactive broker api as a replacement. Interactive brokers seems to offer low commissions and native first party implementations of their python api, plus offering trading functionality.
